#!/usr/bin/env bash
# RunPod: keep Ollama models across pod stop/start using a Network Volume.
#
# WHY: Default pod disk is ephemeral. Stop/terminate = ~12GB models gone (qwen + flux).
# FIX: Network Volume at /workspace survives pod stops. You only pay GPU when running.
#
# RunPod console: https://www.console.runpod.io/user/storage
set -euo pipefail

echo "=============================================="
echo "RunPod model persistence checklist"
echo "=============================================="
echo ""
echo "CURRENT POD (ephemeral disk):"
echo "  Pod ID: fylvirr5y9slvo"
echo "  Models: qwen2.5vl:7b (~6GB) + x/flux2-klein:4b (~6GB)"
echo ""
echo "DO NOT click Stop/Terminate until models are on a Network Volume."
echo ""
echo "=== Step 1: Create Network Volume (one time) ==="
echo "  1. RunPod → Storage → New Network Volume"
echo "  2. Same datacenter as your GPU pod"
echo "  3. Size: 50–100 GB (100 GB recommended)"
echo "  4. Name: gov-copilot-ollama"
echo ""
echo "=== Step 2: Migrate models FROM current pod (while it is still running) ==="
echo "  SSH in and check where models live:"
echo "    du -sh ~/.ollama/models"
echo "    df -h /workspace"
echo ""
echo "  If /workspace is already a network volume (you attached one at deploy):"
echo "    mkdir -p /workspace/ollama/models"
echo "    systemctl stop ollama 2>/dev/null || pkill ollama || true"
echo "    rsync -av ~/.ollama/ /workspace/ollama/"
echo "    export OLLAMA_MODELS=/workspace/ollama/models"
echo "    nohup ollama serve > /tmp/ollama.log 2>&1 &"
echo "    ollama list"
echo ""
echo "=== Step 3: New pod with volume (if current pod has NO volume) ==="
echo "  Network volumes attach ONLY at deploy — not to an existing pod."
echo "  1. Deploy NEW pod → select your Network Volume"
echo "  2. Same GPU (RTX 3090), Secure Cloud"
echo "  3. On OLD pod (still running), copy models to new pod via runpodctl or rsync"
echo "  4. Update core/.env RUNPOD_POD_ID and SSH host"
echo "  5. Terminate OLD pod only after new pod shows: ollama list"
echo ""
echo "=== Step 4: Safe stop when not using GPU ==="
echo "  With models on /workspace/ollama/models:"
echo "    Stop pod → GPU billing stops, models KEEP on volume"
echo "    Start pod → ./big image runpod setup (skips pull if models exist)"
echo ""
echo "=== Step 5: Laptop tunnel (unchanged) ==="
echo "  ssh -N -L 11435:127.0.0.1:11434 runpod-direct"
echo ""
echo "Storage cost: ~\$7/month per 100GB volume (no GPU while stopped)."
echo "=============================================="